######################################################################################
#
# This is my Iosevka Term custom build plan
#
# [Iosevka Customizer](https://be5invis.github.io/Iosevka/customizer)
# [Iosevka Custom Build Doc](https://github.com/be5invis/Iosevka/doc/custom-build.md)
#
######################################################################################

[buildPlans.IosevkaTermCustom]
family = "Iosevka Term Custom"
spacing = "term"

#########################################################################
#
# Sections
#
# Build plan could have 9 optional subsections:
#   - ligations
#   - variants
#   - weights
#   - widths
#   - slopes
#   - compatibilityLigatures
#   - excludeChars
#   - metricOverride
#   - namingOverride
#
#########################################################################

# Widths {{{

[buildPlans.IosevkaTermCustom.widths.Normal]
shape = 550        # Unit Width, measured in 1/1000 em.
menu  = 5          # Width grade for the font's names.
css   = "normal"   # "font-stretch' property of webfont CSS.

# }}}
