######################################################################################
#
# This is my Iosevka-term custom build plan
#
# [Iosevka-term Customizer](https://be5invis.github.io/Iosevka/customizer)
# [Iosevka-term Custom Build Doc](https://github.com/be5invis/Iosevka/doc/custom-build.md)
#
######################################################################################

[buildPlans.iosevka-term-custom]
family = "Iosevka Term Custom"
spacing = "normal"
serifs = "sans"

# Disables `cv##` and `ss##` OpenType features.
no-cv-ss = false

# Whether to export glyph names into the fonts. Setting this to `true` will
# increase file footprint, however this is necessary for ligature support in
# [Kitty](https://sw.kovidgoyal.net/kitty/).
export-glyph-names = true

#########################################################################
#
# Sections
#
# When one of `widths`, `weights`, `slopes` is absent, all
# possible section variants will be generated
#
#########################################################################

# Variants {{{

[buildPlans.iosevka-term-custom.variants.design]
number-sign = "upright-tall"
at = "fourfold-tall"

# }}}


# Ligations {{{

[buildPlans.iosevka-term-custom.ligations]
inherits = "clike"    # inherits an existing ligation set

# }}}


# Widths {{{

[buildPlans.iosevka-term-custom.widths.normal]
shape = 500        # Unit Width, measured in 1/1000 em.
menu  = 5          # Width grade for the font's names.

# }}}


# Weights {{{

[buildPlans.iosevka-term-custom.weights.regular]
shape = 400
menu = 400

[buildPlans.iosevka-term-custom.weights.bold]
shape = 700
menu = 700

# }}}


# Slopes {{{

[buildPlans.iosevka-term-custom.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"

[buildPlans.iosevka-term-custom.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"

# }}}

# # Create ttc {{{
#
# [collectPlans.iosevka-term-custom]
# from = [iosevka-term-custom]
#
# }}}
