on: push

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest release
        uses: octokit/request-action@v2.x
        id: fetch_latest_release
        with:
          route: GET /repos/be5invis/Iosevka/releases/latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Parse version from release tag
        run: echo IOSEVKA_VERSION=$(echo ${{ fromJson(steps.fetch_latest_release.outputs.data).tag_name }} | sed 's/^v//') >> $GITHUB_ENV
      - name: Setup cache
        uses: actions/cache@v2
        id: cache
        with:
          path: '*.ttf'
          key: ${{ env.IOSEVKA_VERSION }}-normal
      - name: Download iosevka
        if: steps.cache.outputs.cache-hit != 'true'
        run: curl -fsSLO https://github.com/be5invis/Iosevka/releases/download/v${{ env.IOSEVKA_VERSION }}/ttf-iosevka-${{ env.IOSEVKA_VERSION }}.zip
      - name: Unzip iosevka
        if: steps.cache.outputs.cache-hit != 'true'
        run: unzip ttf-iosevka-${{ env.IOSEVKA_VERSION }}.zip iosevka-{regular,bold,italic,bolditalic}.ttf
      - name: Remove zip
        if: steps.cache.outputs.cache-hit != 'true'
        run: rm *.zip
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: iosevka
          path: '*.ttf'
      - name: Summary
        run: tree

  release:
    runs-on: ubuntu-latest
    needs: download
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: iosevka
      - name: Create release archives
        run: zip ttf-iosevka.zip *
      - name: Create and upload release
        uses: softprops/action-gh-release@v1
        with:
          name: Iosevka
          tag_name: latest
          files: ttf-iosevka.zip

  patch:
    runs-on: ubuntu-latest
    needs: download
    steps:
      - name: Sparse clone nerd-fonts repo
        run: git clone --filter=blob:none --sparse https://github.com/ryanoasis/nerd-fonts .
      - name: Set sparse-checkout patterns
        run: git sparse-checkout set font-patcher src/glyphs
      - name: Summary
        run: tree
