on: push

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest release
        uses: octokit/request-action@v2.x
        id: fetch_latest_release
        with:
          route: GET /repos/be5invis/Iosevka/releases/latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Parse version from release tag
        run: echo IOSEVKA_VERSION=$(echo ${{ fromJson(steps.fetch_latest_release.outputs.data).tag_name }} | sed 's/^v//') >> $GITHUB_ENV
      - name: Setup cache
        uses: actions/cache@v2
        id: cache
        with:
          path: '*.ttf'
          key: ${{ env.IOSEVKA_VERSION }}-term
      - name: Download iosevka term
        if: steps.cache.outputs.cache-hit != 'true'
        run: curl -fsSLO https://github.com/be5invis/Iosevka/releases/download/v${{ env.IOSEVKA_VERSION }}/ttf-iosevka-term-${{ env.IOSEVKA_VERSION }}.zip
      - name: Unzip iosevka term
        if: steps.cache.outputs.cache-hit != 'true'
        run: unzip ttf-iosevka-term-${{ env.IOSEVKA_VERSION }}.zip iosevka-term-{regular,bold,italic,bolditalic}.ttf
      - name: Remove zip
        if: steps.cache.outputs.cache-hit != 'true'
        run: rm *.zip
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: iosevka-term
          path: '*.ttf'
      - name: Summary
        run: tree

  release:
    runs-on: ubuntu-latest
    needs: download
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: iosevka-term
      - name: Create release archives
        run: zip ttf-iosevka-term.zip *
      - name: Create and upload release
        uses: softprops/action-gh-release@v1
        with:
          name: Iosevka
          tag_name: latest
          files: ttf-iosevka-term.zip

  patch:
    runs-on: ubuntu-latest
    needs: download
    steps:
      - name: Install fontforge build deps
        run: sudo apt-get install libjpeg-dev libtiff5-dev libpng-dev libfreetype6-dev libgif-dev libgtk-3-dev libxml2-dev libpango1.0-dev libcairo2-dev libspiro-dev python3-dev ninja-build cmake build-essential gettext -y -q
      - name: Checkout fontforge
        uses: actions/checkout@v2
        with:
          repository: fontforge/fontforge
          path: fontforge
      - name: Build fontforge from source
        run: |
          mkdir -p fontforge/build && cd fontforge/build
          sudo cmake -GNinja .. && sudo ninja && sudo ninja install
      - name: Delete fontforge artifacts
        run: rm -rf fontforge
      - name: Sparse clone nerd-fonts repo
        run: git clone --filter=blob:none --sparse https://github.com/ryanoasis/nerd-fonts .
      - name: Set sparse-checkout patterns
        run: git sparse-checkout set font-patcher src/glyphs
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: iosevka-term
          path: unpatched
      - name: Save font-patcher arguments
        run: echo NF_ARGS=\"-q --careful --pomicons --fontawesome --fontawesomeextension --material --weather --fontlogos --octicons --codicons\" >> $GITHUB_ENV
      - name: Check args
        run: echo ${{ env.NF_ARGS }}
      - name: Patch fonts
        # use sparse-checkout of repo instead of docker
        # we already have:  --powerline --powerlineextra
        # think about these:  --powersymbols
        run: for font in unpatched/*.ttf; do fontforge -script ./font-patcher -out patched ${{ env.NF_ARGS }} "$font"; done || true
      - name: Summary
        run: tree
      - name: Create release archives
        run: cd patched && zip -r ../ttf-iosevka-term-nf.zip .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Iosevka
          tag_name: latest
          files: ttf-iosevka-term-nf.zip
      - name: Summary
        run: tree
