on:
  push:
  schedule:
    - cron: '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest release
        uses: octokit/request-action@v2.x
        id: fetch_latest_release
        with:
          route: GET /repos/be5invis/Iosevka/releases/latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Parse version from release tag
        run: echo IOSEVKA_VERSION=$(echo ${{ fromJson(steps.fetch_latest_release.outputs.data).tag_name }} | sed 's/^v//') >> $GITHUB_ENV
      - name: Checkout latest release
        uses: actions/checkout@v2
        with:
          repository: be5invis/Iosevka
          ref: v${{ env.IOSEVKA_VERSION }}
      - name: Download private build plan
        run: curl -fsSL "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/src/term.toml" -o private-build-plans.toml
      - name: Setup cache
        uses: actions/cache@v2
        id: cache
        with:
          path: dist/iosevka-term-custom
          key: ${{ env.IOSEVKA_VERSION }}-${{ hashFiles('private-build-plans.toml') }}
      - name: Setup nodejs
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Install npm dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Install ttfautohint
        if: steps.cache.outputs.cache-hit != 'true'
        run: sudo apt-get install ttfautohint -y -q
      - name: Build font
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm run build -- ttf::iosevka-term-custom
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: iosevka-term
          path: dist/iosevka-term-custom/ttf/*
      - name: Summary
        run: tree

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: iosevka-term
      - name: Create release archives
        run: zip ttf-iosevka-term-custom.zip *
      - name: Create and upload release
        uses: softprops/action-gh-release@v1
        with:
          name: Iosevka
          tag_name: latest
          files: ttf-iosevka-term-custom.zip

  patch:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install fontforge build deps
        run: sudo apt-get install libjpeg-dev libtiff5-dev libpng-dev libfreetype6-dev libgif-dev libgtk-3-dev libxml2-dev libpango1.0-dev libcairo2-dev libspiro-dev python3-dev ninja-build cmake build-essential gettext -y -q
      - name: Checkout fontforge
        uses: actions/checkout@v2
        with:
          repository: fontforge/fontforge
          path: fontforge
      - name: Build fontforge from source
        run: |
          mkdir -p fontforge/build && cd fontforge/build
          sudo cmake -GNinja .. && sudo ninja && sudo ninja install
      - name: Delete fontforge artifacts
        run: sudo rm -rf fontforge
      - name: Sparse clone nerd-fonts repo
        run: git clone --filter=blob:none --sparse https://github.com/ryanoasis/nerd-fonts .
      - name: Set sparse-checkout patterns
        run: git sparse-checkout set font-patcher src/glyphs
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: iosevka-term
          path: unpatched
      - name: Patch fonts
        # use sparse-checkout of repo instead of docker
        # we already have:  --powerline --powerlineextra
        # think about these:  --powersymbols
        run: >
          for font in unpatched/*.ttf; do fontforge -script ./font-patcher
          --pomicons
          --fontawesome
          --fontawesomeextension
          --material
          --weather
          --fontlogos
          --octicons
          --codicons
          -out patched -q --careful "$font" 2>/dev/null; done || true
      - name: Create release archives
        run: cd patched && zip -r ../ttf-iosevka-term-custom-nf.zip .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Iosevka
          tag_name: latest
          files: ttf-iosevka-term-custom-nf.zip
      - name: Summary
        run: tree
